server:
  port: 9090

spring:
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: example
      database: user_db
      port: 27018
      host: localhost
      auto-index-creation: true
  application:
    name: authentication-with-keycloak
  mail:
    host: smtp.gmail.com
    port: 587
    username: bugzapper.hrd@gmail.com
    password: dbblamycivtocqki
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.debug: true
  #Resource server configuration
  security:
    oauth2:
      resource server:
        jwt:
          issuer-uri: http://localhost:8080/realms/user
          jwk-set-uri: http://localhost:8080/realms/user/protocol/openid-connect/certs
#          jwk-set-uri: http://localhost:8080/realms/myauth/protocol/openid-connect/certs
# Keycloak configuration
keycloak:
  realm: user
  resource: user-client
  auth-server-url: http://localhost:8080/
  credentials:
    secret: cEZzxdzJXYpr8QGf97hyh9zTJTzulW5O
    client-id: user-client
    provider: secret
# Swagger configuration
springdoc:
  swagger-ui:
    oauth:
      client-id: user-client
      client-secret: cEZzxdzJXYpr8QGf97hyh9zTJTzulW5O
      realm: user
    tags-sorter: alpha