server:
  port: 8081
spring:
  application:
    name: user-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: bugzapper.hrd@gmail.com
    password: dbblamycivtocqki
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  #Resource server configuration
  security:
    oauth2:
      resource server:
        jwt:
          issuer-uri: https://keycloak.jelay.site/realms/stack-notes
#          jwk-set-uri: http://localhost:8080/realms/user/protocol/openid-connect/certs
#          jwk-set-uri: http://localhost:8080/realms/myauth/protocol/openid-connect/certs
# Keycloak configuration
keycloak:
  realm: stack-notes
  resource: stack-notes-client
  auth-server-url: https://keycloak.jelay.site/
  credentials:
    secret: tDbzKXKsHvvmFQAJ1bUSR87Dbia2ssfZ
    client-id: stack-notes-client
    provider: secret
# Swagger configuration
springdoc:
  swagger-ui:
    oauth:
      client-id: stack-notes-client
      client-secret: tDbzKXKsHvvmFQAJ1bUSR87Dbia2ssfZ
      realm: stack-notes
    tags-sorter: alpha
# Eureka configuration
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#    register-with-eureka: true
#    fetch-registry: true
