server:
  port: 9090
spring:
  application:
    name: user-service
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: example
      database: user_db
      port: 27018
      host: localhost
      auto-index-creation: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: bugzapper.hrd@gmail.com
    password: dbblamycivtocqki
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  #Resource server configuration
  security:
    oauth2:
      resource server:
        jwt:
          issuer-uri: https://keycloak.manin.lol/realms/stack-note
#          jwk-set-uri: http://localhost:8080/realms/user/protocol/openid-connect/certs
#          jwk-set-uri: http://localhost:8080/realms/myauth/protocol/openid-connect/certs
# Keycloak configuration
keycloak:
  realm: stack-note
  resource: stack-note-client
  auth-server-url: https://keycloak.manin.lol/
  credentials:
    secret: bRG4XwimHwS8q5kKpyJR2IuXeunW4axw
    client-id: stack-note-client
    provider: secret
# Swagger configuration
springdoc:
  swagger-ui:
    oauth:
      client-id: stack-note-client
      client-secret: bRG4XwimHwS8q5kKpyJR2IuXeunW4axw
      realm: stack-note
    tags-sorter: alpha